name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Gera a cada 12h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    name: Build Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake.svg (dark theme)
        uses: Platane/snk@v3
        with:
          github_user_name: Mikaelbfaa
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark&color_snake=4F46E5&color_dots=#5A5A5A,#6E40C9,#9333EA,#C084FC,#E879F9

      - name: Push generated snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
